spring:
  data:
    redis:
      host: ${REDIS_HOST:redis}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      ssl:
        enabled: ${REDIS_SSL:false}
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
  datasource:
    # Database Connection Settings
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/2do_db}
    username: ${SPRING_DATASOURCE_USERNAME:admin}
    password: ${SPRING_DATASOURCE_PASSWORD:admin}
    driver-class-name: org.postgresql.Driver
  jpa:
    # Logging SQL queries (Disable in production for performance)
    show-sql: true

    # Disable Open Session In View to prevent database connection leaks in the view layer
    open-in-view: false
    hibernate:
      # Automatically updates the database schema (Use 'validate' in production)
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

# Google - Settings & Api-Key
google:
  gemini:
    api-key: ${GEMINI_API_KEY:HERE_IS_YOUR_API_KEY}
    url: https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent

#
# Custom Application Properties
#
application:
  # Metadata for Swagger/OpenAPI documentation
  title: 2DO API
  version: 0.0.1-SNAPSHOT
  description: A scalable, secure and robust Task Management REST API
  contact:
    name: Kaan
    email: kaan403@icloud.com
    url: https://github.com/Kaandroids

  # Security & JWT Configuration
  security:
    jwt:
      # Secret key used for signing JWTs (Must be 256-bit or higher)
      secret-key: ${JWT_SECRET_KEY:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}

      # Access token expiration time in milliseconds (e.g., 86400000 ms = 24 hours)
      expiration: 86400000

      # Refresh token expiration time (e.g., 7 days)
      refresh-token:
        expiration: 604800000

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  api-docs:
    path: /v3/api-docs